"""added citizenships

Revision ID: 33b28a81a63b
Revises: 
Create Date: 2023-12-26 16:42:20.901417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b28a81a63b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('citizenship_idCitizenship', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workers', 'citizenships', ['citizenship_idCitizenship'], ['idCitizenship'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_column('workers', 'citizenship_idCitizenship')
    # ### end Alembic commands ###
